# -*- coding: utf-8 -*-
"""bbb_model/predictor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rqny2wr_srdvvZiNp7GxovNUCGvQBOLD
"""

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

from bbb_model_features_py import canonicalize_smiles, compute_rdkit_descriptors
from bbb_model_utils import load_joblib, load_json


@dataclass
class BBBPredictor:
    artifacts_dir: str = "artifacts"

    def __post_init__(self) -> None:
        self.descriptor_cols = load_json(f"{self.artifacts_dir}/descriptor_cols.json")
        self.stage2_cols = load_json(f"{self.artifacts_dir}/stage2_feature_cols.json")

        self.stage1_efflux = load_joblib(f"{self.artifacts_dir}/models/stage1_efflux.joblib")
        self.stage1_influx = load_joblib(f"{self.artifacts_dir}/models/stage1_influx.joblib")
        self.stage1_pampa = load_joblib(f"{self.artifacts_dir}/models/stage1_pampa.joblib")
        self.stage1_cns = load_joblib(f"{self.artifacts_dir}/models/stage1_cns.joblib")
        self.stage2_bbb = load_joblib(f"{self.artifacts_dir}/models/stage2_bbb.joblib")

    def _X_desc(self, smiles: List[str]) -> pd.DataFrame:
        canon = [canonicalize_smiles(s) for s in smiles]
        if any(c is None for c in canon):
            # keep alignment, but invalid rows become zeros
            canon = [c if c is not None else "" for c in canon]

        X = compute_rdkit_descriptors(canon)

        # align descriptor columns
        for c in self.descriptor_cols:
            if c not in X.columns:
                X[c] = 0.0
        X = X[self.descriptor_cols]
        return X

    def predict_proba(self, smiles: List[str]) -> pd.DataFrame:
        X = self._X_desc(smiles)

        p_eff = self.stage1_efflux.predict_proba(X)[:, 1]
        p_inf = self.stage1_influx.predict_proba(X)[:, 1]
        p_pam = self.stage1_pampa.predict_proba(X)[:, 1]
        p_cns = self.stage1_cns.predict_proba(X)[:, 1]

        X2 = X.copy()
        X2["p_efflux_mech"] = p_eff
        X2["p_influx_mech"] = p_inf
        X2["p_pampa_mech"] = p_pam
        X2["p_cns_mech"] = p_cns

        # align Stage 2 columns
        for c in self.stage2_cols:
            if c not in X2.columns:
                X2[c] = 0.0
        X2 = X2[self.stage2_cols]

        p_bbb = self.stage2_bbb.predict_proba(X2)[:, 1]

        out = pd.DataFrame(
            {
                "smiles": smiles,
                "p_bbb_plus": p_bbb,
                "p_efflux_mech": p_eff,
                "p_influx_mech": p_inf,
                "p_pampa_mech": p_pam,
                "p_cns_mech": p_cns,
            }
        )
        return out

    def predict_label(self, smiles: List[str], threshold: float = 0.5) -> pd.DataFrame:
        out = self.predict_proba(smiles)
        out["bbb_pred"] = (out["p_bbb_plus"].values >= threshold).astype(int)
        return out
