# -*- coding: utf-8 -*-
"""bbb_model/utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rqny2wr_srdvvZiNp7GxovNUCGvQBOLD
"""

import json
import os
from typing import Any, Dict, List, Tuple

import joblib
import numpy as np
import pandas as pd


def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def save_json(obj: Any, path: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2)


def load_json(path: str) -> Any:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_joblib(obj: Any, path: str) -> None:
    joblib.dump(obj, path)


def load_joblib(path: str) -> Any:
    return joblib.load(path)


def load_labeled_csv(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    if "smiles" not in df.columns or "label" not in df.columns:
        raise ValueError(f"{path} must contain columns: smiles, label")
    df = df[["smiles", "label"]].copy()
    df["label"] = df["label"].astype(int)
    return df